### ISSUE TITLE
Current `sentry_link` version is incompatible with latest Sentry version (>=8.0.0)

### ISSUE THREAD

**Issue by ndelanou** [ueman/sentry-dart-tools#12]
pubspec.yaml
```yaml
dependencies:
  ...
  sentry_link: ^0.3.0
  sentry_logging: ^8.0.0
```

```bash
Because sentry_logging >=8.0.0 depends on sentry 8.0.0 and sentry_link 0.3.0 depends on sentry ^7.8.0, sentry_logging
  >=8.0.0 is incompatible with sentry_link 0.3.0.
And because no versions of sentry_link match >0.3.0 <0.4.0, sentry_logging >=8.0.0 is incompatible with sentry_link
  ^0.3.0.
```
